# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 08:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='message text')),
                ('processed', models.BooleanField(default=False, verbose_name='processed')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'message',
                'verbose_name_plural': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('text', models.TextField(verbose_name='message text')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('response', models.TextField(blank=True, null=True, verbose_name='response from GCM')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('date_sent', models.DateTimeField(blank=True, null=True, verbose_name='date sent')),
                ('attempt', models.PositiveSmallIntegerField(blank=True, default=0, null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='notification.Message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'logged message',
                'verbose_name_plural': 'logged messages',
            },
        ),
        migrations.CreateModel(
            name='UserList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('users', models.ManyToManyField(blank=True, related_name='notification_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'verbose_name': 'notification users list',
                'verbose_name_plural': 'notification users lists',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='user_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='notification.UserList'),
        ),
    ]
