# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20151217_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='response',
            field=models.TextField(blank=True, null=True, verbose_name='response from GCM'),
        ),
    ]
