# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0004_auto_20151217_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='success'),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_sent',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date sent'),
        ),
    ]
