# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_auto_20151217_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='processed',
            field=models.BooleanField(default=False, verbose_name='processed'),
        ),
    ]
