# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustomprofile',
            name='gcm_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='GCM ID'),
        ),
    ]
